@startuml

(*) --> "IIoT devices"
if "请求接入网络" then
    --> [有合法账户] "允许接入网络"
    if "请求访问服务" then
        --> [有相应的权限，且评分足够] "允许访问"
        if "入侵检测" then
            --> [判断为正常流量] "提升信任评分"
        else
            -> [判断为异常流量] "降低信任评分"
        endif
    else
        -> [无相应的权限] "降低信任评分"
    endif
else
    -> [无合法账户] "拒绝接入网络"
endif

@enduml
